name: Build Test

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: cache node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install

      - name: build
        run: yarn build

      - name: test
        run: yarn vitest run --passWithNoTests
